name: build-and-test

on: [push, pull_request]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m pytest app/unit_tests.py

  integration-test:

    needs: [unit-test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start app
        run: |
          cd app
          python deploy.py --data_path ./tests/test_data/ &
      - name: integration test
        run: |
          python -m pytest app/tests/integration_tests.py

  e2e-test:

    needs: [integration-test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest selenium==4.11.2
          pip install -r requirements.txt
      - name: Prepare Selenium
        uses: nanasess/setup-chromedriver@v2
      - name: Start XVFB
        run: |
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode
      - name: Start app
        run: |
          cd app
          python deploy.py --data_path ./tests/test_data/ &
      - name: e2e test
        run: |
          sleep 5 && python -m pytest app/tests/e2e_tests.py
